### ISSUE TITLE
Object has been destroyed - Error report for exile-diary 1.0.5

### ISSUE THREAD

**Issue by Naw-Namw** [Qt-dev/exile-diary#175]
Error:
```
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (C:\Users\Naw\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\index.js:434:25)
    at EventEmitter.emit (node:events:513:28)
    at Tail.<anonymous> (C:\Users\Naw\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\build\main\modules\ClientTxtWatcher.js:126:37)
    at Tail.emit (node:events:513:28)
    at C:\Users\Naw\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:56:20
    at Array.forEach (<anonymous>)
    at C:\Users\Naw\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\nodejs-tail\nodejs-tail.js:54:43
    at FSReqCallback.wrapper [as oncomplete] (node:fs:675:5)
```
OS: Windows NT 10.0.19045
App: exile-diary 1.0.5

**Comment by Qt-dev** [comment]
Did this happen long after you updated? 
Could you kill all of the Exile Diary Reborn processes (with that CTRL+ALT+DEL menu) and see if you get that again?

Basically, this error is related to the main window losing track of the Overlay. It should be fixed in 1.0.5 and so I want to make sure the error you are hitting is not related to the 1.0.4 overlay being still there and messing with 1.0.5 after the update

**Comment by Qt-dev** [comment]
I see, interesting. I will keep it around for tracking in case it happens to more then.

I will look into it more and rework that whole thing if it turns out more folks are getting it. Hopefully it does not get to this hehe

**Comment by Qt-dev** [comment]
I think there's a loop that's broken when you update the app, and that's triggering a ton of these, a ton more than expected. I'll close this one because we have a few open on the side with more recent errors. Thanks for reporting!
